# Pandas

## 标签化数据结构
#### 提供带标签的值

## 灵活处理缺失数据
#### 内置nan处理机制

## 智能数据对齐
#### 自动按标签对齐数据

## 强大io工具
#### csv excel sql

## 时间序列处理  
#### 原生支持日期时间处理和频率转换

#### series 一维数据  单索引 同质化数据类型 excel单列
#### pd.Series([1,2,3])
#### dataframe 二维数据 行索引+ 列名  各列可不同数据类型  整张excel工作表
#### pd.DataFrame({'col',[1,2,3]})

In [83]:
import pandas as pd
import numpy as np
#自定义索引
s=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
print(s)
#定义标签
s=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'],name='my_series')
print(s)
#通过字典来创建
s=pd.Series({'a':1,'b':2,'c':3,'d':4,'e':5})
print(s)    
#通过索引去访问元素
s1=pd.Series(s,index=['a','c'])
print(s1)

a    1
b    2
c    3
d    4
e    5
dtype: int64
a    1
b    2
c    3
d    4
e    5
Name: my_series, dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64
a    1
c    3
dtype: int64

### series 的属性
### index 索引对象 values 值 dtype类型 shape 形状 ndim 形状 size 元素个数 name 名称  loc[]显式索引 iloc[]隐式索引 at[] 使用标签访问单个元素 iat[]使用位置访问单个元素

In [84]:
print(s)
print(s.index)
print(s.values)
print(s.dtype)
s.name='my_series'
print(s.name)
print(s.shape,s.ndim,s.size)
#通过标签访问元素
#print(s['a'])   
#print(s['a':'c'])  #切片访问
#通过位置访问元素   
#print(s[0])
#print(s[0:3])  #切片访问
#通过标签访问元素
#print(s.loc['a'])   !!!!显式索引是看标签，隐式索引是看位置!!!
#print(s.loc['a':'c'])  #切片访问
#通过位置访问元素
#rint(s.iloc[0])
#print(s.iloc[0:3])  #切片访问 
#print(s.at['a']) #通过标签访问单个元素
#print(s.iat[0]) #通过位置访问单个元素

a    1
b    2
c    3
d    4
e    5
dtype: int64
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
[1 2 3 4 5]
int64
my_series
(5,) 1 5

In [85]:
#series访问数据
print(s['a'])
print(s[s>2])     #访问大于2的元素

1
c    3
d    4
e    5
Name: my_series, dtype: int64

### head()查看前n行默认5 tail查看后n行默认5
### isin()  判断元素是否在参数集合中    isna()判断是否为缺失值如（nan 或none）
### sum mean min max var std median 
### mode()众数可返回多个 quantile(q)分位数 describe()常见统计信息
### value_counts() 每个唯一值的出现次数 count()非缺失值数量 nunique()唯一值个数（去重）
### unique() 获取去重后的值数组  drop_duplicates() 去除重复项   sample()  随机抽样 
### sort_index()按索引排序 sort_values()按值排序 repalce()替换值 keys() 返回series的索引对象

In [86]:
s=pd.Series([10,2,np.nan,None,3,4,5],index=['a','b','c','d','e','f','g'])
print(s)
s.name='data'

a    10.0
b     2.0
c     NaN
d     NaN
e     3.0
f     4.0
g     5.0
dtype: float64

In [87]:
print(s.head())  #默认显示前5行
print(s.tail())  #默认显示后5行

a    10.0
b     2.0
c     NaN
d     NaN
e     3.0
Name: data, dtype: float64
c    NaN
d    NaN
e    3.0
f    4.0
g    5.0
Name: data, dtype: float64

In [88]:
print(s.isna())  #判断是否为缺失值
#print(s.notna()) #判断是否为非缺失值
#print(s.isnull())  #判断是否为缺失值
#print(s.notnull()) #判断是否为非缺失值

a    False
b    False
c     True
d     True
e    False
f    False
g    False
Name: data, dtype: bool

In [89]:
#查看描述性信息
print(s.describe()) #count忽略缺失值
print(s.keys())  #返回索引标签 通过方法
#print(s.index)  #返回索引标签  通过属性
print(s.values)  #返回数据值

count     5.000000
mean      4.800000
std       3.114482
min       2.000000
25%       3.000000
50%       4.000000
75%       5.000000
max      10.000000
Name: data, dtype: float64
Index(['a', 'b', 'c', 'd', 'e', 'f', 'g'], dtype='object')
[10.  2. nan nan  3.  4.  5.]

In [90]:
print(s.isin([10, 2]))  #判断元素是否在列表中

a     True
b     True
c    False
d    False
e    False
f    False
g    False
Name: data, dtype: bool

In [91]:
print(s.sort_values())  #按值排序
print(s.sort_index())   #按索引排序

b     2.0
e     3.0
f     4.0
g     5.0
a    10.0
c     NaN
d     NaN
Name: data, dtype: float64
a    10.0
b     2.0
c     NaN
d     NaN
e     3.0
f     4.0
g     5.0
Name: data, dtype: float64

In [92]:
#众数
s['h']=10
s['i']=2
print(s.mode()  )

0     2.0
1    10.0
Name: data, dtype: float64

In [93]:
print(s.value_counts())  #统计每个值出现的次数

data
10.0    2
2.0     2
3.0     1
4.0     1
5.0     1
Name: count, dtype: int64

In [94]:
print(s.drop_duplicates())  #去重返回series
print(s.unique())  #返回列表

a    10.0
b     2.0
c     NaN
e     3.0
f     4.0
g     5.0
Name: data, dtype: float64
[10.  2. nan  3.  4.  5.]

In [95]:
print(s.dropna())  #删除缺失值
print(s.fillna(0))  #填充缺失值为0

a    10.0
b     2.0
e     3.0
f     4.0
g     5.0
h    10.0
i     2.0
Name: data, dtype: float64
a    10.0
b     2.0
c     0.0
d     0.0
e     3.0
f     4.0
g     5.0
h    10.0
i     2.0
Name: data, dtype: float64

In [96]:
np.random.seed(44)
score=pd.Series(np.random.randint(50,101,size=10),index=['学生'+str(i) for i in range(1,11)],name='score')
print(score)

学生1     70
学生2     85
学生3     99
学生4     95
学生5     53
学生6     82
学生7     70
学生8     53
学生9     97
学生10    92
Name: score, dtype: int32

In [97]:
print(score.mean())  #平均值
print(score.max())  #最大值
print(score.min())  #最小值 
print((score>=score.mean()).sum())  #统计大于平均值的元素个数
s1=score[score>=score.mean()]  #访问大于平均值的元素
print(s1)  #访问大于平均值的元素

79.6
99
53
6
学生2     85
学生3     99
学生4     95
学生6     82
学生9     97
学生10    92
Name: score, dtype: int32

In [114]:
#找出学生成绩变化最大的学生
score_diff=score.diff()  #计算成绩的差分
  #按值排序
print(score_diff)  #查看成绩变化
print(score_diff.sort_values(ascending=False)[0:2])  #查看成绩变化最大的前两名

学生1      NaN
学生2     15.0
学生3     14.0
学生4     -4.0
学生5    -42.0
学生6     29.0
学生7    -12.0
学生8    -17.0
学生9     44.0
学生10    -5.0
Name: score, dtype: float64
学生9    44.0
学生6    29.0
Name: score, dtype: float64

In [121]:
price=pd.Series([102.3,103.5,105.1,104.8,106.2,107.0,106.5,108.1,109.3,110.2],index=pd.date_range('2024-01-01', periods=10),name='price')
print(price)

2024-01-01    102.3
2024-01-02    103.5
2024-01-03    105.1
2024-01-04    104.8
2024-01-05    106.2
2024-01-06    107.0
2024-01-07    106.5
2024-01-08    108.1
2024-01-09    109.3
2024-01-10    110.2
Freq: D, Name: price, dtype: float64

In [130]:
#计算价格的日收益率 当日收盘价-前日收盘价 -1
returns=price.pct_change()  #计算日收益率
returns.fillna(0, inplace=True)  #填充第一个元素为0
print(returns)  #查看日收益率
print('最大日收益率: {:.2f}%'.format(returns.max()*100))  #查看最大日收益率    
print('最小日收益率: {:.2f}%'.format(returns.min()*100))  #查看最小日收益率
print('日收益率标准差: {:.2f}%'.format(returns.std()*100))  #查看日收益率的标准差
print('最大日收益率日期: {}'.format(returns.idxmax()))  #查看最大日收益率的日期
print('最小日收益率日期: {}'.format(returns.idxmin()))  #查看最小日收益率的日期

2024-01-01    0.000000
2024-01-02    0.011730
2024-01-03    0.015459
2024-01-04   -0.002854
2024-01-05    0.013359
2024-01-06    0.007533
2024-01-07   -0.004673
2024-01-08    0.015023
2024-01-09    0.011101
2024-01-10    0.008234
Freq: D, Name: price, dtype: float64
最大日收益率: 1.55%
最小日收益率: -0.47%
日收益率标准差: 0.74%
最大日收益率日期: 2024-01-03 00:00:00
最小日收益率日期: 2024-01-07 00:00:00

In [ ]:
sales=pd.Series([120,135,145,160,155,170,180,175,190,200,210,220]
                ,index=pd.date_range('2024-01-01', periods=12,freq='MS'),name='sales')#freq ='me'是月尾 ‘W’按周
print(sales)# 每个月份的销售额

2024-01-01    120
2024-02-01    135
2024-03-01    145
2024-04-01    160
2024-05-01    155
2024-06-01    170
2024-07-01    180
2024-08-01    175
2024-09-01    190
2024-10-01    200
2024-11-01    210
2024-12-01    220
Freq: MS, Name: sales, dtype: int64

In [ ]:
#季度的平均销量
print(sales.resample('QS').mean()) #重新采样' YS'年初 ‘QS’季度初
print(sales.resample('QS').sum()) #重新采样

2024-01-01    133.333333
2024-04-01    161.666667
2024-07-01    181.666667
2024-10-01    210.000000
Freq: QS-JAN, Name: sales, dtype: float64
2024-01-01    400
2024-04-01    485
2024-07-01    545
2024-10-01    630
Freq: QS-JAN, Name: sales, dtype: int64

In [162]:
#最大销量
print(sales.idxmax(),sales.max())
#月环比的增长率
a=sales.pct_change()
b=a>0
b[b.rolling(3).sum()==3].keys().tolist()#滑动窗口

2024-12-01 00:00:00 220

[Timestamp('2024-04-01 00:00:00'),
 Timestamp('2024-11-01 00:00:00'),
 Timestamp('2024-12-01 00:00:00')]

## DataFrame

In [6]:
#dataframe_create
import pandas as pd
import numpy as np
# 通过series创建dataframe
s1=pd.Series([1,2,3],index=['a','n','c'],name='s1')
s2=pd.Series([4,5,6],index=['a','b','c'],name='s2')
df=pd.DataFrame({'First':s1,'Second':s2})  
print(type(df))  #查看数据类型
print(df)

<class 'pandas.core.frame.DataFrame'>
   First  Second
a    1.0     4.0
b    NaN     5.0
c    3.0     6.0
n    2.0     NaN

In [ ]:
#通过字典来创建
df=pd.DataFrame({"id":[1,2,3,4,5],"name":['Alice','Bob','Charlie','David','Eve'],
                 "age":[25,30,35,40,45],"score":[80.4,85.2,90.5,88.0,92.3]},
                index=['a','b','c','d','e'],columns=['id','name','score','age'])  #指定索引
print(df)

   id     name  score  age
a   1    Alice   80.4   25
b   2      Bob   85.2   30
c   3  Charlie   90.5   35
d   4    David   88.0   40
e   5      Eve   92.3   45

## DataFrame 的属性

In [14]:
print(df.index)  #查看索引
print(df.columns)  #查看列标签
print(df.values)  #查看数据值

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
Index(['id', 'name', 'score', 'age'], dtype='object')
[[1 'Alice' 80.4 25]
 [2 'Bob' 85.2 30]
 [3 'Charlie' 90.5 35]
 [4 'David' 88.0 40]
 [5 'Eve' 92.3 45]]

In [15]:
print(df.ndim)  #查看维度
print(df.shape)  #查看形状  
print(df.dtypes)  #查看每列的数据类型
print(df.size)  #查看元素个数

2
(5, 4)
id         int64
name      object
score    float64
age        int64
dtype: object
20

In [17]:
#行列转置
print(df.T)
print(df.T.index)

           a     b        c      d     e
id         1     2        3      4     5
name   Alice   Bob  Charlie  David   Eve
score   80.4  85.2     90.5   88.0  92.3
age       25    30       35     40    45
Index(['id', 'name', 'score', 'age'], dtype='object')

In [21]:
#获取元素 loc iloc at iat
#某行
print(df.loc['e'])
print(df.iloc[4])
#某列
print(df.loc[:, 'name'])
print(df.iloc[:, 1] )

id          5
name      Eve
score    92.3
age        45
Name: e, dtype: object
id          5
name      Eve
score    92.3
age        45
Name: e, dtype: object
a      Alice
b        Bob
c    Charlie
d      David
e        Eve
Name: name, dtype: object
a      Alice
b        Bob
c    Charlie
d      David
e        Eve
Name: name, dtype: object

In [24]:
#单个元素

print(df.at['e','name'])
print(df.iat[4,1])

Eve
Eve

In [29]:
# 获取单列数据
print(df['name'])  #访问列
print(type(df['name']))  #查看数据类型
print(df.name)
print(df[['name']])#dataframe 数据类型
print(df[['name','age']])#访问多列数据

a      Alice
b        Bob
c    Charlie
d      David
e        Eve
Name: name, dtype: object
<class 'pandas.core.series.Series'>
a      Alice
b        Bob
c    Charlie
d      David
e        Eve
Name: name, dtype: object
      name
a    Alice
b      Bob
c  Charlie
d    David
e      Eve
      name  age
a    Alice   25
b      Bob   30
c  Charlie   35
d    David   40
e      Eve   45

In [31]:
#查看部分数据
print(df.head(3))
print(df.tail(3))

   id     name  score  age
a   1    Alice   80.4   25
b   2      Bob   85.2   30
c   3  Charlie   90.5   35
   id     name  score  age
c   3  Charlie   90.5   35
d   4    David   88.0   40
e   5      Eve   92.3   45

In [38]:

df[(df.score>80) & (df.age>30)]#可以用. 也可以用[]

   id     name  score  age
c   3  Charlie   90.5   35
d   4    David   88.0   40
e   5      Eve   92.3   45

In [41]:
print(df.sample(frac=0.5, random_state=1))  #随机抽样50%的数据
print(df.sample(n=3, random_state=1))  #随机抽样3行数据
#随机抽样

   id     name  score  age
c   3  Charlie   90.5   35
b   2      Bob   85.2   30
   id     name  score  age
c   3  Charlie   90.5   35
b   2      Bob   85.2   30
e   5      Eve   92.3   45

In [43]:
print(df.isin(['jack']))  #判断元素是否在列表中
print(df.isna())  #判断元素是否为缺失值

      id   name  score    age
a  False  False  False  False
b  False  False  False  False
c  False  False  False  False
d  False  False  False  False
e  False  False  False  False
      id   name  score    age
a  False  False  False  False
b  False  False  False  False
c  False  False  False  False
d  False  False  False  False
e  False  False  False  False

In [50]:
print(df['score'].sum())  #计算score列的总和
print(df['score'].mean())  #计算score列的平均值
print(df['score'].max())  #计算score列的最大值  
print(df['score'].min())  #计算score列的最小值

436.40000000000003
87.28
92.3
80.4

In [53]:
print(df['score'].std())  #计算score列的标准差
print(df['score'].count())  #计算score列的非缺失值个数
print(df['score'].median())  #计算score列的中位数

4.683695122443386
5
88.0

In [57]:
print(df.value_counts())  #统计每行出现的次数
print(df.drop_duplicates())  #去重返回dataframe
print(df.duplicated(subset=['age']))  #判断每行是否重复

id  name     score  age
1   Alice    80.4   25     1
2   Bob      85.2   30     1
3   Charlie  90.5   35     1
4   David    88.0   40     1
5   Eve      92.3   45     1
Name: count, dtype: int64
   id     name  score  age
a   1    Alice   80.4   25
b   2      Bob   85.2   30
c   3  Charlie   90.5   35
d   4    David   88.0   40
e   5      Eve   92.3   45
a    False
b    False
c    False
d    False
e    False
dtype: bool

In [ ]:

print(df['score'].quantile(0.25))  #计算score列的第25百分位数
print(df['score'].mode())  #计算score列的众数
print(df['score'].describe())  #查看score列的描述性统计信息

4.683695122443386
5
88.0
85.2
0    80.4
1    85.2
2    88.0
3    90.5
4    92.3
Name: score, dtype: float64
count     5.000000
mean     87.280000
std       4.683695
min      80.400000
25%      85.200000
50%      88.000000
75%      90.500000
max      92.300000
Name: score, dtype: float64

In [61]:
df.cumsum()
#df.cumsum(axis=0)  #按列累加
#df.cumsum(axis=1)  #按行累加 字符串会报错

   id                     name  score  age
a   1                    Alice   80.4   25
b   3                 AliceBob  165.6   55
c   6          AliceBobCharlie  256.1   90
d  10     AliceBobCharlieDavid  344.1  130
e  15  AliceBobCharlieDavidEve  436.4  175

In [70]:
print(df.sort_index(ascending=True))  #按索引排序
print(df.sort_values(by=['age','score'], ascending=[False, True]))  #按age和score列的值排序 if age 相同则按score排序

   id     name  score  age
a   1    Alice   80.4   25
b   2      Bob   85.2   30
c   3  Charlie   90.5   35
d   4    David   88.0   40
e   5      Eve   92.3   45
   id     name  score  age
e   5      Eve   92.3   45
d   4    David   88.0   40
c   3  Charlie   90.5   35
b   2      Bob   85.2   30
a   1    Alice   80.4   25

In [72]:
print(df.nlargest(3, 'score'))  #返回score列最大的3行数据
print(df.nsmallest(3, 'score'))  #返回score列最小的3行数据

   id     name  score  age
e   5      Eve   92.3   45
c   3  Charlie   90.5   35
d   4    David   88.0   40
   id   name  score  age
a   1  Alice   80.4   25
b   2    Bob   85.2   30
d   4  David   88.0   40